version: "3"

services:
  grafana:
    image: "grafana/grafana:${TAG-latest}"
    ports:
      - 3000:3000
    environment:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_USER: "<my@email.adddress>"
      GF_SMTP_PASSWORD: "<my_smtp_pass_here>"
      GF_SMTP_HOST: "<smtp_host_here:25>"
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    volumes:
      - "${PWD-.}/grafana:/var/lib/grafana"

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - "${PWD-.}/elasticsearch:/usr/share/elasticsearch/data"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.1
    volumes:
      - "${PWD-.}/logstash:/usr/share/logstash/pipeline"
      - "${PWD-.}/data:/data"
